POST http://localhost:4400/user/create
Content-Type: application/json

{
    "fullName":"Daniel Kitheka",
    "userName":"Dantez",
    "email":"kkinyidk@gmail.com",
    "phoneNumber":"0712345678",
    "location":"Nyeri, Kenya",
    "password":"12345678"
}