POST http://localhost:4400/user/create
Content-Type: application/json

{
    "fullName":"Daniel Kitheka",
    "userName":"Dan1234",
    "email":"abcd_254_003@yopmail.com",
    "phoneNumber":12345678,
    "password":"12345678"
}

###
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "email":"kakinyidk@gmail.com", 
    "password":"12345678"
}

###
GET http://localhost:4400/user/getUsers
Content-Type: application/json

###
POST http://localhost:4400/parcel/create
Content-Type: application/json

{
        "sender":"alex123@gmail.com",
        "parcelWeight":2,
        "price":200,
        "lat":-1.567,
        "lng":36.45,
        "senderLat":-1.45,
        "senderLng":40.45,
        "parcelDescription":"test",
        "receiverLocation":"test",
        "receiverPhone":"745244141",
        "receiverEmail":"abc@gmail.com",
        "deliveryDate":"22122022"
}


###
GET http://localhost:4400/parcel/allparcels
Content-Type: application/json

###
GET http://localhost:4400/user/check
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJRCI6MTAwMiwiZnVsbE5hbWUiOiJEYW5pZWwgS2l0aGVrYSIsInVzZXJOYW1lIjoiRGFuMSIsImVtYWlsIjoia2FraW55aWRrMUBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6MTIzNDU2NzgsImxvY2F0aW9uIjoiTnllcmksIEtlbnlhIiwibGF0IjoxMiwibG5nIjozMywid2VsY29tZSI6Ik5PIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjMwOTIxMTIsImV4cCI6MTY2MzA5MjQxMn0.pWS-TLVofYUpAFgiLyTXaiKgcMr8LtY3oG27X2Ufjw8

###
POST http://localhost:4400/user/setLocation
Content-Type: application/json

{
    "email":"kakinyidk1@gmail.com",
    "lat":12.234,
    "lng":33.27
}

###
GET http://localhost:4400/parcel/delete/3020
Content-Type: application/json

###
PUT http://localhost:4400/parcel/update/7
Content-Type: application/json

{       
        "sender":"xyz@gmail.com",
        "parcelWeight":3,
        "price":750,
        "lat":-1.567,
        "lng":36.45,
        "senderLat":-1.45,
        "senderLng":40.45,
        "parcelDescription":"Electronics",
        "receiverLocation":"Nairobi",
        "receiverPhone":7072441418,
        "receiverEmail":"abcde@GMAIL.COM",
        "deliveryDate":"2213321"
}
###
PUT http://localhost:4400/parcel/updateStatus/3020
Content-Type: application/json

{
    "status":"Delivered"
}


###
PUT http://localhost:4400/user/update/2
Content-Type: application/json

{
    "fullName":"Daniel K",
    "phoneNumber": 12345678,
    "password":"12345678"
}