POST http://localhost:4400/user/create
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJRCI6MiwiZnVsbE5hbWUiOiJEYW5pZWwgSyIsInVzZXJOYW1lIjoiRGFuaWVsIiwiZW1haWwiOiJrYWtpbnlpZGtAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIxMjM0NTY3OCIsImxhdCI6MSwibG5nIjozOCwid2VsY29tZSI6IllFUyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MzU4OTcxNywiZXhwIjoxNjYzNTkwMDE3fQ.vERBQvNELjdE4LocjAPJikKcu_qOleE5Tca7DDTpbOY

{
    "fullName":"Daniel Kitheka",
    "userName":"Dan1234",
    "email":"abcd_254_003@yopmail.com",
    "phoneNumber":12345678,
    "password":"12345678"
}

###
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "email":"kakinyidk@gmail.com", 
    "password":"12345678"
}

###
GET http://localhost:4400/user/getUsers
Content-Type: application/json

###
POST http://localhost:4400/parcel/create
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJRCI6MiwiZnVsbE5hbWUiOiJEYW5pZWwgSyIsInVzZXJOYW1lIjoiRGFuaWVsIiwiZW1haWwiOiJrYWtpbnlpZGtAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIxMjM0NTY3OCIsImxhdCI6MSwibG5nIjozOCwid2VsY29tZSI6IllFUyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MzU5MDIxOCwiZXhwIjoxNjYzNTkwNTE4fQ.-z1eN5TC5AfA4EFN3g7Ury71rhnPUL6MaJxaBS8Y0uc

{
        "sender":"alex123@gmail.com",
        "parcelWeight":2,
        "price":200,
        "lat":-1.567,
        "lng":36.45,
        "senderLat":-1.45,
        "senderLng":40.45,
        "parcelDescription":"test",
        "receiverLocation":"test",
        "receiverPhone":"745244141",
        "receiverEmail":"abc@gmail.com",
        "deliveryDate":"22122022"
}


###
GET http://localhost:4400/parcel/allparcels
Content-Type: application/json
token:

###
GET http://localhost:4400/user/check
Content-Type: application/json
token:

###
POST http://localhost:4400/user/setLocation
Content-Type: application/json

{
    "email":"kakinyidk1@gmail.com",
    "lat":12.234,
    "lng":33.27
}

###
DELETE http://localhost:4400/parcel/delete/3019
Content-Type: application/json
token:

###
PUT http://localhost:4400/parcel/update/7
Content-Type: application/json

{       
        "sender":"xyz@gmail.com",
        "parcelWeight":3,
        "price":750,
        "lat":-1.567,
        "lng":36.45,
        "senderLat":-1.45,
        "senderLng":40.45,
        "parcelDescription":"Electronics",
        "receiverLocation":"Nairobi",
        "receiverPhone":7072441418,
        "receiverEmail":"abcde@GMAIL.COM",
        "deliveryDate":"2213321"
}
###
PUT http://localhost:4400/parcel/updateStatus/3020
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJRCI6MiwiZnVsbE5hbWUiOiJEYW5pZWwgSyIsInVzZXJOYW1lIjoiRGFuaWVsIiwiZW1haWwiOiJrYWtpbnlpZGtAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIxMjM0NTY3OCIsImxhdCI6MSwibG5nIjozOCwid2VsY29tZSI6IllFUyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MzU5MDUyOSwiZXhwIjoxNjYzNTkwODI5fQ.cNoBHT8P0jB_KjKJ2p9RVgnX7g7fOFLs0ODLjuhUcL0

{
    "status":"Delivered"
}


###
PUT http://localhost:4400/user/update/2
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJRCI6MiwiZnVsbE5hbWUiOiJEYW5pZWwgSyIsInVzZXJOYW1lIjoiRGFuaWVsIiwiZW1haWwiOiJrYWtpbnlpZGtAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIxMjM0NTY3OCIsImxhdCI6MSwibG5nIjozOCwid2VsY29tZSI6IllFUyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MzU5MDUyOSwiZXhwIjoxNjYzNTkwODI5fQ.cNoBHT8P0jB_KjKJ2p9RVgnX7g7fOFLs0ODLjuhUcL0

{
    "fullName":"Daniel K",
    "phoneNumber": 12345678,
    "password":"12345678"
}