CREATE TABLE CLIENTS(
clientID INT NOT NULL PRIMARY KEY IDENTITY (1,1), 
fullName VARCHAR(200) NOT NULL, 
userName VARCHAR(200) NOT NULL UNIQUE, 
email VARCHAR(200) NOT NULL UNIQUE,
phoneNumber INT, 
location VARCHAR(200) NOT NULL, 
password VARCHAR(200) NOT NULL,
welcome VARCHAR(200) DEFAULT 'NO')